server:
 port: 8080
 servlet:
  encoding:
   charset: UTF-8
   
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: list # tag, operation 펼치는 방식

spring:
 profiles:
  active: local
 config.import: sm://
 sql:
  init:
   mode: EMBEDDED
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER
 web:
    resources:
      add-mappings: false
 jpa:
   open-in-view: false

logging:
  pattern.console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr([${LOG_LEVEL_PATTERN:%5p}]) %clr([%10.10X{mberId}]){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

---
spring:
  config:
    activate:
      on-profile: local
      
---
spring:
  config:
    activate:
      on-profile: dev