server:
 port: 8080
   
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
    filter: true

spring:
 data:
   redis:
     port: ${sm://redis-port}
     host: ${sm://redis-url}
     password: ${sm://db-pwd}
 datasource:
  master:
   hikari:
    driver-class-name: org.postgresql.Driver
    jdbc-url: ${sm://jdbc-url}
    username: app_user
    password: ${sm://db-pwd}
    read-only: false
  slave: # DB replication 적용 후 replica DB로 정보 수정
   hikari:
    driver-class-name: org.postgresql.Driver
    jdbc-url: ${sm://jdbc-url}
    username: app_user
    password: ${sm://db-pwd}
    read-only: true
 jpa:
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  defer-datasource-initialization: true
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER
 web:
    resources:
      add-mappings: false
 ai:
    openai:
      api-key: ${sm://openai-key}
      embedding:
        options:
          model: text-embedding-3-small

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr([${LOG_LEVEL_PATTERN:%5p}]) %clr([%10.10X{userId}]){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: info
    com:
      playground: debug
    org:
      springframework:
        messaging: debug
        core:
          LocalVariableTableParameterNameDiscoverer: error

decorator:
  datasource:
    exclude-beans: dataSource
    p6spy:
      enable-logging: true

CRYPTO_PWD: ${sm://crypto-pwd}
CRYPTO_SALT: ${sm://crypto-pwd}

CLIENT_URL: http://localhost:3000
