runtime: java17
instance_class: F2
entrypoint: 'java -jar ./build/libs/playground-0.0.1.jar'

automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 1000

env_variables:
 spring_profiles_active: "dev"
