runtime: java17
instance_class: F1
entrypoint: 'java -jar -Xms128m -Xmx256m -XX:MaxMetaspaceSize=64m -XX:MinMetaspaceFreeRatio=20 -XX:MaxMetaspaceFreeRatio=40 ./build/libs/playground-0.0.1.jar'

automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 1000

env_variables:
 spring_profiles_active: "dev"
 JAVA_OPS: "-Xms128m -Xmx256m -XX:MaxMetaspaceSize=64m -XX:MinMetaspaceFreeRatio=20 -XX:MaxMetaspaceFreeRatio=40"
