runtime: java17
instance_class: F1
entrypoint: 'java -jar -Xms128m -Xmx320m -XX:MaxMetaspaceSize=80m -XX:MinMetaspaceFreeRatio=20 -XX:MaxMetaspaceFreeRatio=80 ./build/libs/playground-0.0.1.jar'

automatic_scaling:
  min_instances: 1
  max_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 1000

env_variables:
 spring_profiles_active: "dev"
