runtime: java17
instance_class: F1
entrypoint: 'java -jar ./build/libs/playground.jar'
handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1

env_variables:
 spring_profiles_active: "dev"
