runtime: java17
instance_class: F2
entrypoint: 'ls -al & java -jar ./build/libs/playground.jar'

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
 spring_profiles_active: "dev"
